package message

import (
	"errors"
	"fmt"
	"github.com/datastax/go-cassandra-native-protocol/cassandraprotocol/primitive"
	"io"
)

type Startup struct {
	Options map[string]string
}

type StartupCustomizer func(*Startup)

func NewStartup(customizers ...StartupCustomizer) *Startup {
	startup := &Startup{map[string]string{"CQL_VERSION": "3.0.0"}}
	for _, customizer := range customizers {
		customizer(startup)
	}
	return startup
}

func WithCompression(compression string) StartupCustomizer {
	return func(startup *Startup) {
		startup.Options["COMPRESSION"] = compression
	}
}

// Currently supported options are:
// - "CQL_VERSION"
// - "COMPRESSION"
// Starting with DSE v2 the following options are also recognized:
// - "CLIENT_ID": string representation of the client instance. Recommended is a ID unique per runtime instance
//   (e.g. DataStax Java Driver's CqlSession instance), generated by the driver.
// - "APPLICATION_NAME": optional, name of the application, should include the vendor name.
//   For example "DataStax Studio".
// - "APPLICATION_VERSION": optional, version of the application.
// - "DRIVER_NAME": product name of the driver implementation. For example: 'DataStax Java Driver'.
// - "DRIVER_VERSION": version of the driver implementation, typically a semantic version string.
func WithOptions(options map[string]string) StartupCustomizer {
	return func(startup *Startup) {
		for key, value := range options {
			startup.Options[key] = value
		}
	}
}

func (m *Startup) IsResponse() bool {
	return false
}

func (m *Startup) GetOpCode() primitive.OpCode {
	return primitive.OpCodeStartup
}

func (m *Startup) String() string {
	return fmt.Sprint("STARTUP ", m.Options)
}

type StartupCodec struct{}

func (c *StartupCodec) Encode(msg Message, dest io.Writer, _ primitive.ProtocolVersion) error {
	startup, ok := msg.(*Startup)
	if !ok {
		return errors.New(fmt.Sprintf("expected *message.Startup, got %T", msg))
	}
	return primitive.WriteStringMap(startup.Options, dest)
}

func (c *StartupCodec) EncodedLength(msg Message, _ primitive.ProtocolVersion) (int, error) {
	startup, ok := msg.(*Startup)
	if !ok {
		return -1, errors.New(fmt.Sprintf("expected *message.Startup, got %T", msg))
	}
	return primitive.LengthOfStringMap(startup.Options), nil
}

func (c *StartupCodec) Decode(source io.Reader, _ primitive.ProtocolVersion) (Message, error) {
	if options, err := primitive.ReadStringMap(source); err != nil {
		return nil, err
	} else {
		return &Startup{Options: options}, nil
	}
}

func (c *StartupCodec) GetOpCode() primitive.OpCode {
	return primitive.OpCodeStartup
}
