// Code generated by mockery v2.12.3. DO NOT EDIT.

package datacodec

import mock "github.com/stretchr/testify/mock"

// mockKeyValueInjector is an autogenerated mock type for the keyValueInjector type
type mockKeyValueInjector struct {
	mock.Mock
}

// setElem provides a mock function with given fields: index, key, value, keyWasNull, valueWasNull
func (_m *mockKeyValueInjector) setElem(index int, key interface{}, value interface{}, keyWasNull bool, valueWasNull bool) error {
	ret := _m.Called(index, key, value, keyWasNull, valueWasNull)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, interface{}, interface{}, bool, bool) error); ok {
		r0 = rf(index, key, value, keyWasNull, valueWasNull)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// zeroElem provides a mock function with given fields: index, key
func (_m *mockKeyValueInjector) zeroElem(index int, key interface{}) (interface{}, error) {
	ret := _m.Called(index, key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(int, interface{}) interface{}); ok {
		r0 = rf(index, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, interface{}) error); ok {
		r1 = rf(index, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// zeroKey provides a mock function with given fields: index
func (_m *mockKeyValueInjector) zeroKey(index int) (interface{}, error) {
	ret := _m.Called(index)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(int) interface{}); ok {
		r0 = rf(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type newMockKeyValueInjectorT interface {
	mock.TestingT
	Cleanup(func())
}

// newMockKeyValueInjector creates a new instance of mockKeyValueInjector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockKeyValueInjector(t newMockKeyValueInjectorT) *mockKeyValueInjector {
	mock := &mockKeyValueInjector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
