// Code generated by mockery v2.12.3. DO NOT EDIT.

package datacodec

import mock "github.com/stretchr/testify/mock"

// mockKeyValueExtractor is an autogenerated mock type for the keyValueExtractor type
type mockKeyValueExtractor struct {
	mock.Mock
}

// getElem provides a mock function with given fields: index, key
func (_m *mockKeyValueExtractor) getElem(index int, key interface{}) (interface{}, error) {
	ret := _m.Called(index, key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(int, interface{}) interface{}); ok {
		r0 = rf(index, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, interface{}) error); ok {
		r1 = rf(index, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getKey provides a mock function with given fields: index
func (_m *mockKeyValueExtractor) getKey(index int) interface{} {
	ret := _m.Called(index)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(int) interface{}); ok {
		r0 = rf(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

type newMockKeyValueExtractorT interface {
	mock.TestingT
	Cleanup(func())
}

// newMockKeyValueExtractor creates a new instance of mockKeyValueExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockKeyValueExtractor(t newMockKeyValueExtractorT) *mockKeyValueExtractor {
	mock := &mockKeyValueExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
